### ISSUE TITLE
安装fabric-go插件时出错，错误日志如下

### ISSUE THREAD

**Issue by choice1987** [xuchengli/fabric-go#1]
this.statusBarView.dispose is not a function
Hide Stack Trace
TypeError: this.statusBarView.dispose is not a function
    at Object.destroyStatusBar (file:///C:/Users/admin/.atom/packages/fabric-go/lib/fabric-go.js:64:26)
    at Object.setStatusbar (file:///C:/Users/admin/.atom/packages/fabric-go/lib/fabric-go.js:49:10)
    at Object.consumeStatusBar (file:///C:/Users/admin/.atom/packages/fabric-go/lib/fabric-go.js:70:10)
    at Provider.provide (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:14:1121906)
    at ServiceHub.consume (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:11:3315037)
    at Package.activateServices (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:11:3323269)
    at Package.activateNow (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:11:3320024)
    at measure (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:11:3319348)
    at Package.measure (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:11:3316958)
    at activationPromise.activationPromise.Promise (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:11:3319208)
    at new Promise (<anonymous>)
    at Package.activate (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:11:3319151)
    at PackageManager.activatePackage (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:11:382452)
    at C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:11:941081
    at r (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:11:935687)
    at n (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:14:1124813)
    at ChildProcess.o.process.on.e (C:\applicationSoftware\Atom x64\resources\app\static\<embedded>:14:1125019)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

**Comment by xuchengli** [comment]
你下载最新的 0.1.7 的版本安装，然后重新打开一下 atom 试试。
